version: '3.8'
services:
  fastapi:
    build: ./backend
    environment:
      - .env
    ports:
      - 7777:7777
    depends_on:
      - db
    volumes:
      - ./fast_api:/fast_api/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local